---
services:
  web:
    build:
      context: .
    env_file:
    - .env
    volumes:
    - ./src/html:/var/www/html
    - ./src/lib:/var/www/lib
    - ./config:/var/www/config
    ports:
    - "3000:80"

  apache-exporter:
    image: bitnami/apache-exporter:latest@sha256:9f4309c873ac3ba31f9c05646908a82fe7a34165701e4907330af5e9ac0e793a
    command: [ "--scrape_uri=http://web:81/server-status?auto" ]
    depends_on:
      - web
    profiles:
      - monitoring
